### ISSUE TITLE
Xyce support

### ISSUE THREAD

**Issue by thou1940** [snishizawa/libretto#4]
Does it support Xyce as the simulator instead of Xyce?
it appears not as it show errors 

`start thread :0
start thread :1
start thread :2
Exception in thread 0:
start thread :3
Traceback (most recent call last):
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
Exception in thread 2:
    self.run()
Exception in thread 1:
Traceback (most recent call last):
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1010, in run
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
Traceback (most recent call last):
Exception in thread 3:
Traceback (most recent call last):
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1010, in run
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1010, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 335, in runSpiceCombDelaySingle
    self._target(*self._args, **self._kwargs)
  File "/home/tenmiles/app/miniconda3/envs/hwintern/lib/python3.12/threading.py", line 1010, in run
    = genFileLogic_trial1(targetLib, targetCell, targetHarness, 0, cap_line, slew_line, temp_line, "none", "none", spicefo)
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 335, in runSpiceCombDelaySingle
    self._target(*self._args, **self._kwargs)
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 335, in runSpiceCombDelaySingle
    = genFileLogic_trial1(targetLib, targetCell, targetHarness, 0, cap_line, slew_line, temp_line, "none", "none", spicefo)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = genFileLogic_trial1(targetLib, targetCell, targetHarness, 0, cap_line, slew_line, temp_line, "none", "none", spicefo)
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 335, in runSpiceCombDelaySingle
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 685, in genFileLogic_trial1
    = genFileLogic_trial1(targetLib, targetCell, targetHarness, 0, cap_line, slew_line, temp_line, "none", "none", spicefo)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    outlines.append(cmd)
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 685, in genFileLogic_trial1
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 685, in genFileLogic_trial1
    outlines.append(cmd)
                    ^^^
UnboundLocalError: cannot access local variable 'cmd' where it is not associated with a value
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 685, in genFileLogic_trial1
                    ^^^
    outlines.append(cmd)
UnboundLocalError: cannot access local variable 'cmd' where it is not associated with a value
    outlines.append(cmd)
                    ^^^
UnboundLocalError: cannot access local variable 'cmd' where it is not associated with a value
                    ^^^
UnboundLocalError: cannot access local variable 'cmd' where it is not associated with a value
0
{}
Traceback (most recent call last):
  File "/home/tenmiles/app/libretto-main/libretto.py", line 623, in <module>
    main()
  File "/home/tenmiles/app/libretto-main/libretto.py", line 286, in main
    harnessList2 = characterizeFiles(targetLib, targetCell)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tenmiles/app/libretto-main/libretto.py", line 328, in characterizeFiles
    return runCombIn1Out1(targetLib, targetCell, expectationList2,"neg")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 37, in runCombIn1Out1
    runSpiceCombDelayMultiThread(targetLib, targetCell, tmp_Harness, spicef)
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 267, in runSpiceCombDelayMultiThread
    targetLib.print_msg(str(results_prop_in_out[str(thread_id)]))
                            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '0'`

**Comment by snishizawa** [comment]
Currently, Xyce is not supported. Only ngspice and hspice are supported.
