### ISSUE TITLE
unknown error 

### ISSUE THREAD

**Issue by thou1940** [snishizawa/libretto#5]
I tried ngpsice and run a inverter, it gives me error that some values is not defined. I didn't find them in the yaml parameter list. so i am confused about this errors.

errors are as followed

start thread :0 
start thread :1 
start thread :2 
start thread :3 
Value res_prop_in_out is not defined!! 
Check simulation result in work directory 
Value res_prop_in_out is not defined!! 
Check simulation result in work directory 
Value res_prop_in_out is not defined!! 
Check simulation result in work directory 
Value res_prop_in_out is not defined!! 
Check simulation result in work directory 
0 
{} 
Traceback (most recent call last):
  File "/home/tenmiles/app/libretto-main/libretto.py", line 623, in <module>
    main()
  File "/home/tenmiles/app/libretto-main/libretto.py", line 286, in main
    harnessList2 = characterizeFiles(targetLib, targetCell)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tenmiles/app/libretto-main/libretto.py", line 328, in characterizeFiles
    return runCombIn1Out1(targetLib, targetCell, expectationList2,"neg")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 37, in runCombIn1Out1
    runSpiceCombDelayMultiThread(targetLib, targetCell, tmp_Harness, spicef)
  File "/home/tenmiles/app/libretto-main/char_comb.py", line 267, in runSpiceCombDelayMultiThread
    targetLib.print_msg(str(results_prop_in_out[str(thread_id)]))
                            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '0'

**Comment by snishizawa** [comment]
Value "res_prop_in_out" is not defined, please check simulation result. It seems your circuit does not generate expected output. 
libretto generates spice file with ".sp" extension. ".sp.lis" is the log file from your simulator. You can see waveform activating .control statement on generated spice file.
